### ISSUE TITLE
env var export and make_package script 

### ISSUE THREAD

**Issue by mitmor** [mcgillij/mcgillij.dev#1]
content/aur_with_chroot.rst describes exporting BUILD_CHROOT as:

`export BUILD_CHROOT=$HOME/aur_build_chroot`

the `make_package` script runs:

`makechrootpkg -c -r $HOME/$BUILD_CHROOT`

which extrapolates to:

`/home/<user>//home/<user>/aur_build_chroot`

**Comment by mcgillij** [comment]
derp good catch

**Comment by mcgillij** [comment]
fixed.
